In [1]:
import numpy as np

In [ ]:
# ob = np.array([22,17,20,26,22,13])
# ex = np.array([20,20,20,20,20,20])

In [ ]:
# ob-ex

array([ 2, -3,  0,  6,  2, -7])

In [ ]:
# np.sum(np.square(ob-ex)/ex)

5.1000000000000005

In [10]:
row1 = np.array([40,45,25,10])
row2 = np.array([35,30,20,30])

In [17]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_row = np.array([sum_r1, sum_r2])
sum_row

array([120, 115])

In [16]:
sum_col = row1 + row2
sum_col

array([75, 75, 45, 40])

In [ ]:
exp = []
for i in sum_row:
    for j in sum_col:
        value = (i*j)/235
        exp.append(value)
    

In [ ]:
obj  = np.array([40,45,25,10,35,30,20,30])

array([40, 45, 25, 10, 35, 30, 20, 30])

In [30]:
np.sum((np.square(obj - exp)) / exp)

13.788747987117553