In [1]:
 # Array - Homogenous array of fixed size
import numpy as np

In [7]:
l1 = [20, 30, 40]
l2 = [60,70,80]
print(l1 + l2)

[20, 30, 40, 60, 70, 80]


In [10]:
a = np.array(l1)
b = np.array(l2)
print(l1)
print(l2)


[20, 30, 40]
[60, 70, 80]


In [11]:
print("Harnoor Kaur")

Harnoor Kaur


In [16]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [20]:
print(arr[0 : 3])
print(arr[1 : 4])
print(arr[:3])

[10 20 30]
[20 30 40]
[10 20 30]


In [22]:
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

(5,)
5
1
int64
