In [1]:
 # Array - Homogenous array of fixed size
import numpy as np

In [7]:
l1 = [20, 30, 40]
l2 = [60,70,80]
print(l1 + l2)

[20, 30, 40, 60, 70, 80]


In [10]:
a = np.array(l1)
b = np.array(l2)
print(l1)
print(l2)


[20, 30, 40]
[60, 70, 80]


In [11]:
print("Harnoor Kaur")

Harnoor Kaur


In [16]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [20]:
print(arr[0 : 3])
print(arr[1 : 4])
print(arr[:3])

[10 20 30]
[20 30 40]
[10 20 30]


In [22]:
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

(5,)
5
1
int64


In [1]:
import numpy as np

In [5]:
a = [30, 40, 50, 50, 40]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(type(arr))
print(arr.dtype)
print(arr.astype(float))


[30 40 50 50 40]
(5,)
5
1
<class 'numpy.ndarray'>
int64
[30. 40. 50. 50. 40.]


In [10]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60, 70, 80, 90, 100])
print(arr1 + arr2)
print(np.add(arr1, arr2))

[ 70  90 110 130 150]
[ 70  90 110 130 150]


In [12]:
# 2D Array
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
arr4 = np.array([[70, 80, 90], [100, 110, 120]])
print(arr3 + arr4)  
print(np.add(arr3, arr4))
print(np.subtract(arr3, arr4))

[[ 80 100 120]
 [140 160 180]]
[[ 80 100 120]
 [140 160 180]]
[[-60 -60 -60]
 [-60 -60 -60]]


In [8]:
print(np.subtract(arr1, arr2))

[-50 -50 -50 -50 -50]


In [13]:
arr1 = np.array([9, 16, 25, 36, 49])
print(np.sqrt(arr1))

[3. 4. 5. 6. 7.]


In [17]:
a = [30, 40, 50]
b = [5, 5, 3]
arr1 = np.array(a)
arr2 = np.array(b)
print(np.concatenate([arr1, arr2]))
print(np.concatenate([arr1, arr2], axis=0))
print(np.hstack([arr1, arr2]))
print(np.vstack([arr1, arr2]))


[30 40 50  5  5  3]
[30 40 50  5  5  3]
[30 40 50  5  5  3]
[[30 40 50]
 [ 5  5  3]]


In [21]:
a = np.array([10, 20, 30, 40, 50])
print(a)
b = np.array_split(a, 5)
print(b)

[10 20 30 40 50]
[array([10]), array([20]), array([30]), array([40]), array([50])]
