In [2]:
import numpy as np
print(np.__version__)

2.4.0


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
a = np.array(42);
b = np.array([1, 2, 3, 4, 5]);
c = np.array([[1, 2, 3], [4, 5, 6]]);
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]);
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[3])
print(arr[2] + arr[4])

4
8


In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 3])
print('last element on 2nd row: ', arr[1, -1])

2nd element on 1st row:  2
5th element on 2nd row:  9
last element on 2nd row:  10


In [15]:
# Slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])
print(arr[0:5:2])
print(arr[:3])
print(arr[2:])
print(arr[::2])
print(arr[:-3])

[2 3 4]
[1 3 5]
[1 2 3]
[3 4 5]
[1 3 5]
[1 2]


In [18]:
a = 'cgc'
b = a[::-1]
print(a == b)

True


In [24]:
a2 = np.array([[1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'], ['abc', 'def', 'ghi', 'jkl', 'mno']])
np.shape(a2)
print(a2)
print(a2[0, 3])
print(a2[1, 4])
print(a2[2, 0])
print(a2[0, 1:4])



[['1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e']
 ['abc' 'def' 'ghi' 'jkl' 'mno']]
4
e
abc
['2' '3' '4']


In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:3, 2])
print(arr[0:2, 1:4])
print(arr.dtype)

[3 8]
[[2 3 4]
 [7 8 9]]
int64


In [ ]:
# Topic 1 
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a2 = np.array([0, 0, 0, 0, 0])
a3 = np.array([1, 1, 1, 1, 1, 1, 1, 1])
a4 = np.array(100)
a5 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
a6 = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19])
a7 = np.arange(5,51,5)
a8 = np.arange(0, 1, 0.1)
a9 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]]) 
a10 = np.array([[[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]]) 
a11 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
a12 = np.full((2, 5), 7)
a13 = np.random.random((3, 3))
a14 = np.random.random((4, 5))
print(a13)
print(a14.shape)
print(a1.dtype)


# Topic 2
print(a1.shape)
print(a10.ndim)
print(a2.size)
print(a13.dtype)
a15 = np.array([3.5, 4.5, 5.5])
print(a15.astype(int))
print(a1.astype(float))
print(len(a6))
a16 = np.array([[1, 2, 3, 4, 5], ['one', 'two', 'three', 'four', 'five']])
print(a16.size)
print(memoryview(a16)) 
a17 = np.array([1, 2, 3, 4, 5])
a18 = np.array([[1, 2, 3], [4, 5, 6]])
print(a17.ndim)
print(a18.ndim)






[[0.88971966 0.29044292 0.29717225]
 [0.91686669 0.58980218 0.80057874]
 [0.52710314 0.12126819 0.99092078]]
(4, 5)
int64
(10,)
3
5
float64
[3 4 5]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
10
10
1
2
1
10
3
[1 2 3]
[10  9  8]
[10  9  8  7  6  5  4  3  2  1]
[3 4 5 6 7]
[1 3 5 7 9]
[1 2 3 4 5]
[21 22 23 24 25]
[ 1  6 11 16 21]
[ 5 10 15 20 25]
5
1
5


In [54]:
# Topic 3
a19 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a19[0])
print(a19[-1])
print(a19[2])
print(a19[0:3])
print(a19[-1:-4:-1])
print(a19[::-1])
print(a19[2:7])
print(a19[::2])
a20 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
print(a20[0])
print(a20[-1])
print(a20[:, 0])
print(a20[:, -1])
a21 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a21[1, 1])
a22 = np.array([[1, 2], [4, 5]] )
print(a22[0, 0])
print(a22[1, 1])

1
10
3
[1 2 3]
[10  9  8]
[10  9  8  7  6  5  4  3  2  1]
[3 4 5 6 7]
[1 3 5 7 9]
[1 2 3 4 5]
[21 22 23 24 25]
[ 1  6 11 16 21]
[ 5 10 15 20 25]
5
1
5


In [56]:
# Topic 4 
a23 = np.array([1, 2, 3, 4, 5])
a24 = np.array([10, 20, 30, 40, 50])
print(a23 + a24)
print(a24 - a23)
print(a23 * a24)
print(a24 / a23)
print(a23 ** 2)
print(a23 ** 3)
print(np.sqrt(a23))
print(np.exp(a23))
print(np.log(a23))
print(np.sin(a23))
print(np.cos(a23))
print(np.tan(a23))
print(np.abs(a23))
print(a23 % 2)
print(a23 ** 5)


[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]
[  1   8  27  64 125]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
[1 2 3 4 5]
[1 0 1 0 1]
[   1   32  243 1024 3125]


In [5]:
# Topic 5
import numpy as np
a25 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.sum(a25))
print(np.mean(a25))
print(np.median(a25))
print(np.max(a25))
print(np.min(a25))
print(np.std(a25))
print(np.var(a25))

# Cumulative sum
print(np.cumsum(a25))
print(np.prod(a25))
print(np.mean(a25[:5]))
a26 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(a26, axis=1)) 
print(np.sum(a26, axis=0))
print(np.mean(a26, axis=1))
print(np.mean(a26, axis=0))
print(np.max(a25) - np.min(a25))



55
5.5
5.5
10
1
2.8722813232690143
8.25
[ 1  3  6 10 15 21 28 36 45 55]
3628800
3.0
[ 6 15 24]
[12 15 18]
[2. 5. 8.]
[4. 5. 6.]
9


In [3]:
# Copy And View
arr = np.array([4, 5, 6, 78, 34])
x = arr.copy()
arr[2] = 89
print(arr)
print(x)

[ 4  5 89 78 34]
[ 4  5  6 78 34]


In [4]:
arr = np.array([4, 5, 6, 78, 34])
y = arr.view()
arr[2] = 89
print(arr)
print(y)

[ 4  5 89 78 34]
[ 4  5 89 78 34]


In [6]:
# Shape of array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
# Topic 6
a27 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 34])
newa27 = a27.reshape(3, 4);
print(newa27)

a28 = np.array([91, 72, 3, 34, 65, 16, 27, 48, 9, 60, 34, 45])
newa28 = a28.reshape(2, 6);
print(newa28)

a29 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 34, 22])
newa29 = a29.reshape(4, 3);
print(newa29)

# Flatten 
a30 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
newa30 = a30.reshape(-1)
print(newa30)

print(np.transpose(newa27))

a31 = np.array([3, 56, 88, 33, 23])
newa31 = a31.reshape(5, 1)
print(newa31)

# Reshape an array using -1
a32 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newa32 = a32.reshape(-1, 3) # meaning -> 3 columns and as many rows as needed
print(newa32)

newnewa27 = newa27.reshape(2, 6)
print(newnewa27)

a33 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# in 1D array
newa33 = a33.reshape(-1) # meaning -> 1 column and as many rows as needed
print(newa33)

a34 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(np.transpose(a34))


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 34]]
[[91 72  3 34 65 16]
 [27 48  9 60 34 45]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 34 22]]
[1 2 3 4 5 6 7 8 9]
[[ 2 10 18]
 [ 4 12 20]
 [ 6 14 22]
 [ 8 16 34]]
[[ 3]
 [56]
 [88]
 [33]
 [23]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6  8 10 12]
 [14 16 18 20 22 34]]
[1 2 3 4 5 6 7 8 9]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [20]:
# Topic 7
a35 = np.array([3, 56, 88, 33, 23])
a36 = np.array([5, 23, 56, 44, 12])
print(np.concatenate((a35, a36)))

# Horizontal stacking
a37 = np.array([1, 2, 3, 4, 5])
a38 = np.array([6, 7, 8, 9, 10])
print(np.hstack((a37, a38))) # hstack means horizontal stacking, it is same as concatenate

# Vertical stacking
a39 = np.array([[1, 2, 3], [4, 5, 6]])
a40 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.vstack((a39, a40))) # vstack means vertical stacking 

print(np.hstack((a35, a36)))
a41 = np.array([2, 4, 6, 8, 10, 12])
print(np.split(a41, 2))

a42 = np.array([1, 34, 56, 78, 90, 12, 23, 45])
print(np.split(a42, 4))


[ 3 56 88 33 23  5 23 56 44 12]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 3 56 88 33 23  5 23 56 44 12]
[array([2, 4, 6]), array([ 8, 10, 12])]
[array([ 1, 34]), array([56, 78]), array([90, 12]), array([23, 45])]


In [30]:
# Topic 8
a43 = np.array([78, 99, 76, 12, 10, 8, 45])
print("Value greater than 10: ")
for x in a43:
    if x > 10:
        print(x)

print("Even numbers: ")
for x in a43:
    if x%2 == 0:
        print(x)

print("Odd numbers: ")
for x in a43:
    if x%2 != 0:
        print(x)


a44 = np.array([-1, -2, -3, -4, -5, 0, 1, 2, 3, 4, 5])
print("Negative numbers: ")
for x in a44:
    if x < 0:
        print(x)

print("Values greater than Mean")
for x in a44:
    if x > np.mean(a44):
        print(x)

#	Replace values greater than 50 with 0. 
a45 = np.array([23, 45, 67, 89, 12, 34, 56, 78])
for i in range(len(a45)):
    if a45[i] > 50:
        a45[i] = 0
print(a45)


Value greater than 10: 
78
99
76
12
45
Even numbers: 
78
76
12
10
8
Odd numbers: 
99
45
Negative numbers: 
-1
-2
-3
-4
-5
Values greater than Mean
1
2
3
4
5
[23 45  0  0 12 34  0  0]


In [32]:
# Topic 9
a46 = np.array([23, 45, 67, 89, 12, 34, 56, 78])
print(np.sort(a46))

a47 = np.array([[3, 56, 88], [33, 23, 45]])
print(np.sort(a47, axis=1))

a48 = np.array([[3, 56, 28], [33, 23, 39]])
print(np.sort(a48, axis=0))

# Index of maximum value
print(np.argmax(a46))
# Index of minimum value
print(np.argmin(a46))

# Find all unique values
a49 = np.array([1, 2, 3, 4, 5, 1, 2, 3])
print(np.unique(a49))



[12 23 34 45 56 67 78 89]
[[ 3 56 88]
 [23 33 45]]
[[ 3 23 28]
 [33 56 39]]
3
4
[1 2 3 4 5]
